/**
 * open_pr MCP Tool
 * 
 * Creates GitHub pull requests with auto-generated checklists from acceptance criteria
 * Implements Phase 4.5 PR hygiene improvements
 */

import { Logger } from 'pino';
import { validateInput, OpenPrSchema, OpenPrInput } from '../lib/validation.js';
import { withRetry, prisma } from '../lib/database.js';
import { getGitHubClient } from '../lib/github.js';
import { ToolResult, OpenPrResponse } from '../types/mcp.js';
import { success, failure, isFailure, NotFoundError, ConflictError, ValidationError } from '../types/errors.js';

/**
 * Generate PR title from task title
 */
function generatePrTitle(taskTitle: string, taskId: number): string {
  // Keep title concise but descriptive
  const maxLength = 72; // GitHub's recommended max for PR titles
  if (taskTitle.length <= maxLength) {
    return taskTitle;
  }
  
  // Truncate and add task ID for context
  const truncated = taskTitle.substring(0, maxLength - 10).trim();
  return `${truncated}... (#${taskId})`;
}

/**
 * Generate PR body with checklist from acceptance criteria
 * Implements Phase 4.5 specification for PR hygiene
 */
function generatePrBody(task: any, acceptanceCriteria: string[]): string {
  const body = `## Description

${task.description}

## Acceptance Criteria

${acceptanceCriteria.map(criteria => `- [ ] ${criteria}`).join('\n')}

## Task Information

- **Task ID**: #${task.id}
- **Assignee**: ${task.assignee || 'Unassigned'}
- **Repository**: ${task.repo || 'Not specified'}

## Review Checklist

- [ ] All acceptance criteria are met
- [ ] Code follows project conventions
- [ ] Tests are included and passing
- [ ] Documentation is updated if needed
- [ ] No breaking changes or properly documented

---

*This PR was automatically generated by TaskHub MCP Server*
*Task: ${task.title}*`;

  return body;
}

/**
 * Open a pull request for a task
 */
export async function openPrTool(args: unknown, logger: Logger): Promise<ToolResult> {
  logger.debug('Processing open_pr request', { args });

  // Validate input
  const validationResult = validateInput(OpenPrSchema, args);
  if (isFailure(validationResult)) {
    logger.warn('open_pr validation failed', { 
      error: validationResult.error,
      args 
    });
    
    return {
      content: [
        {
          type: 'text',
          text: JSON.stringify({
            error: {
              type: validationResult.error.type,
              message: validationResult.error.message,
              code: validationResult.error.code,
              details: validationResult.error.details,
            },
          }),
        },
      ],
      isError: true,
    };
  }

  const input = validationResult.data;
  const requestId = Math.random().toString(36).substring(2, 8);
  
  logger.info('Processing open_pr request', {
    requestId,
    taskId: input.task_id,
    repo: input.repo,
    draft: input.draft,
    dryRun: input.dry_run,
  });

  try {
    // Get GitHub client
    const githubClientResult = getGitHubClient();
    if (isFailure(githubClientResult)) {
      logger.error('Failed to get GitHub client', {
        requestId,
        error: githubClientResult.error,
      });

      return {
        content: [
          {
            type: 'text',
            text: JSON.stringify({
              error: {
                type: githubClientResult.error.type,
                message: githubClientResult.error.message,
                code: githubClientResult.error.code,
                details: githubClientResult.error.details,
              },
            }),
          },
        ],
        isError: true,
      };
    }

    const githubClient = githubClientResult.data;

    // Use database retry wrapper for the PR creation operation
    const prResult = await withRetry(async () => {
      // Get task details
      const task = await prisma.task.findUnique({
        where: { id: input.task_id },
        select: {
          id: true,
          title: true,
          description: true,
          status: true,
          assignee: true,
          repo: true,
          branch: true,
          acceptanceCriteria: true,
        },
      });

      if (!task) {
        throw new NotFoundError(
          `Task with ID ${input.task_id} not found`,
          'TASK_NOT_FOUND',
          { taskId: input.task_id }
        );
      }

      // Check if task is in the right status for PR creation
      if (task.status !== 'in_progress') {
        throw new ConflictError(
          `Task ${input.task_id} must be in progress to create a PR`,
          'TASK_NOT_IN_PROGRESS',
          { 
            taskId: input.task_id,
            currentStatus: task.status,
            requiredStatus: 'in_progress',
          }
        );
      }

      // Check if task has a branch
      if (!task.branch) {
        throw new ConflictError(
          `Task ${input.task_id} does not have a branch. Run start_branch first.`,
          'TASK_NO_BRANCH',
          { taskId: input.task_id }
        );
      }

      // Use provided repo or task's repo
      const repoString = input.repo || task.repo;
      if (!repoString) {
        throw new ValidationError(
          'Repository must be specified either in the request or in the task',
          'REPO_REQUIRED',
          { taskId: input.task_id }
        );
      }

      // Parse repository string
      const repoParts = repoString.split('/');
      if (repoParts.length !== 2 || !repoParts[0] || !repoParts[1]) {
        throw new ValidationError(
          'Repository must be in format "owner/repo"',
          'INVALID_REPO_FORMAT',
          { repo: repoString }
        );
      }

      const repo = { owner: repoParts[0], repo: repoParts[1] };

      // Parse acceptance criteria
      let acceptanceCriteria: string[] = [];
      try {
        acceptanceCriteria = JSON.parse(task.acceptanceCriteria || '[]');
      } catch (error) {
        logger.warn('Failed to parse acceptance criteria', { 
          taskId: task.id,
          acceptanceCriteria: task.acceptanceCriteria,
        });
      }

      // Generate PR title and body
      const prTitle = input.title || generatePrTitle(task.title, task.id);
      const prBody = generatePrBody(task, acceptanceCriteria);

      // Determine if PR should be draft (Phase 4.5 policy)
      const isDraft = input.force ? (input.draft ?? false) : (input.draft ?? true);

      // Create the pull request
      const createPrResult = await githubClient.createPullRequest({
        repo,
        title: prTitle,
        body: prBody,
        head: task.branch,
        draft: isDraft,
        dryRun: input.dry_run || false,
      });

      if (isFailure(createPrResult)) {
        throw createPrResult.error;
      }

      const pr = createPrResult.data;

      // Update task status to review
      const updatedTask = await prisma.task.update({
        where: { id: input.task_id },
        data: {
          status: 'review',
          updatedAt: new Date(),
        },
      });

      // Log the PR creation event
      await prisma.event.create({
        data: {
          taskId: input.task_id,
          actor: task.assignee || 'system',
          action: 'pr_opened',
          payload: JSON.stringify({
            pr_number: pr.number,
            pr_url: pr.url,
            title: pr.title,
            draft: pr.draft,
            repo: repoString,
            branch: task.branch,
            dry_run: input.dry_run || false,
            timestamp: new Date().toISOString(),
          }),
        },
      });

      return {
        task: updatedTask,
        pr,
        repo: repoString,
      };
    });

    if (isFailure(prResult)) {
      logger.error('Failed to create pull request', {
        requestId,
        taskId: input.task_id,
        error: prResult.error,
      });

      return {
        content: [
          {
            type: 'text',
            text: JSON.stringify({
              error: {
                type: prResult.error.type,
                message: prResult.error.message,
                code: prResult.error.code,
                details: prResult.error.details,
              },
            }),
          },
        ],
        isError: true,
      };
    }

    const result = prResult.data;

    const response: OpenPrResponse = {
      task_id: result.task.id,
      pr_number: result.pr.number,
      repo: result.repo,
      title: result.pr.title,
      url: result.pr.url,
      draft: result.pr.draft,
      branch_name: result.pr.head.ref,
      status: result.task.status as any,
      dry_run: input.dry_run || false,
      created_at: new Date().toISOString(),
    };

    logger.info('Pull request created successfully', {
      requestId,
      taskId: result.task.id,
      prNumber: result.pr.number,
      url: result.pr.url,
      draft: result.pr.draft,
      dryRun: input.dry_run,
    });

    return {
      content: [
        {
          type: 'text',
          text: JSON.stringify(response),
        },
      ],
    };
  } catch (error) {
    logger.error('Unexpected error in open_pr', {
      requestId,
      taskId: input.task_id,
      error: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined,
    });

    return {
      content: [
        {
          type: 'text',
          text: JSON.stringify({
            error: {
              type: 'internal',
              message: 'Internal server error while creating pull request',
              code: 'INTERNAL_ERROR',
              details: { requestId },
            },
          }),
        },
      ],
      isError: true,
    };
  }
}
