/**
 * open_pr MCP Tool
 *
 * Creates GitHub pull requests with auto-generated checklists from acceptance criteria
 * Implements Phase 4.5 PR hygiene improvements
 */

import { Logger } from 'pino';
import { validateInput, OpenPrSchema, OpenPrInput } from '../lib/validation.js';
import { withRetry, prisma } from '../lib/database.js';
import { getGitHubClient } from '../lib/github.js';
import { ToolResult, OpenPrResponse } from '../types/mcp.js';
import {
  success,
  failure,
  isFailure,
  NotFoundError,
  ConflictError,
  ValidationError,
} from '../types/errors.js';

/**
 * Generate PR title from task title
 */
function generatePrTitle(taskTitle: string, taskId: number): string {
  // Keep title concise but descriptive
  const maxLength = 72; // GitHub's recommended max for PR titles
  if (taskTitle.length <= maxLength) {
    return taskTitle;
  }

  // Truncate and add task ID for context
  const truncated = taskTitle.substring(0, maxLength - 10).trim();
  return `${truncated}... (#${taskId})`;
}

/**
 * Generate PR body with checklist from acceptance criteria
 * Implements Phase 4.5 specification for PR hygiene
 */
function generatePrBody(task: any, acceptanceCriteria: string[]): string {
  const body = `## Description

${task.description}

## Acceptance Criteria

${acceptanceCriteria.map(criteria => `- [ ] ${criteria}`).join('\n')}

## Task Information

- **Task ID**: #${task.id}
- **Assignee**: ${task.assignee || 'Unassigned'}
- **Repository**: ${task.repo || 'Not specified'}

## Review Checklist

- [ ] All acceptance criteria are met
- [ ] Code follows project conventions
- [ ] Tests are included and passing
- [ ] Documentation is updated if needed
- [ ] No breaking changes or properly documented

---

*This PR was automatically generated by TaskHub MCP Server*
*Task: ${task.title}*`;

  return body;
}

/**
 * Open a pull request for a task
 */
export async function openPrTool(args: unknown, logger: Logger): Promise<ToolResult> {
  logger.debug('Processing open_pr request', { args });

  // Validate input
  const validationResult = validateInput(OpenPrSchema, args);
  if (isFailure(validationResult)) {
    logger.warn('open_pr validation failed', {
      error: validationResult.error,
      args,
    });

    return {
      content: [
        {
          type: 'text',
          text: JSON.stringify({
            error: {
              type: validationResult.error.type,
              message: validationResult.error.message,
              code: validationResult.error.code,
              details: validationResult.error.details,
            },
          }),
        },
      ],
      isError: true,
    };
  }

  const input = validationResult.data;
  const requestId = Math.random().toString(36).substring(2, 8);

  logger.info('Processing open_pr request', {
    requestId,
    taskId: input.task_id,
    repo: input.repo,
    draft: input.draft,
    dryRun: input.dry_run,
  });

  try {
    // Get GitHub client
    const githubClientResult = getGitHubClient();
    if (isFailure(githubClientResult)) {
      logger.error('Failed to get GitHub client', {
        requestId,
        error: githubClientResult.error,
      });

      return {
        content: [
          {
            type: 'text',
            text: JSON.stringify({
              error: {
                type: githubClientResult.error.type,
                message: githubClientResult.error.message,
                code: githubClientResult.error.code,
                details: githubClientResult.error.details,
              },
            }),
          },
        ],
        isError: true,
      };
    }

    const githubClient = githubClientResult.data;

    // 1) Get task (no retry) and validate preconditions
    const task = await prisma.task.findUnique({
      where: { id: input.task_id },
      select: {
        id: true,
        title: true,
        description: true,
        status: true,
        assignee: true,
        repo: true,
        branch: true,
        acceptanceCriteria: true,
      },
    });

    if (!task) {
      return {
        content: [
          { type: 'text', text: JSON.stringify({ error: { type: 'not_found', code: 'TASK_NOT_FOUND', message: `Task with ID ${input.task_id} not found`, details: { taskId: input.task_id } } }) },
        ],
        isError: true,
      };
    }

    if (task.status !== 'in_progress') {
      return {
        content: [
          { type: 'text', text: JSON.stringify({ error: { type: 'conflict', code: 'TASK_NOT_IN_PROGRESS', message: `Task ${input.task_id} must be in progress to create a PR`, details: { taskId: input.task_id, currentStatus: task.status, requiredStatus: 'in_progress' } } }) },
        ],
        isError: true,
      };
    }

    if (!task.branch) {
      return {
        content: [
          { type: 'text', text: JSON.stringify({ error: { type: 'conflict', code: 'TASK_NO_BRANCH', message: `Task ${input.task_id} does not have a branch. Run start_branch first.`, details: { taskId: input.task_id } } }) },
        ],
        isError: true,
      };
    }

    const repoString = input.repo || task.repo;
    if (!repoString) {
      return {
        content: [
          { type: 'text', text: JSON.stringify({ error: { type: 'validation', code: 'REPO_REQUIRED', message: 'Repository must be specified either in the request or in the task', details: { taskId: input.task_id } } }) },
        ],
        isError: true,
      };
    }

    const repoParts = repoString.split('/');
    if (repoParts.length !== 2 || !repoParts[0] || !repoParts[1]) {
      return {
        content: [
          { type: 'text', text: JSON.stringify({ error: { type: 'validation', code: 'INVALID_REPO_FORMAT', message: 'Repository must be in format "owner/repo"', details: { repo: repoString } } }) },
        ],
        isError: true,
      };
    }
    const repo = { owner: repoParts[0], repo: repoParts[1] } as const;

    // Parse acceptance criteria (best effort)
    let acceptanceCriteria: string[] = [];
    try {
      acceptanceCriteria = JSON.parse(task.acceptanceCriteria || '[]');
    } catch {
      logger.warn('Failed to parse acceptance criteria', { taskId: task.id });
    }

    const prTitle = input.title || generatePrTitle(task.title, task.id);
    const prBody = generatePrBody(task, acceptanceCriteria);

    const isDraft = input.force ? (input.draft ?? false) : (input.draft ?? true);

    // 2) Create PR on GitHub (no DB retry here)
    const createPrResult = await githubClient.createPullRequest({
      repo,
      title: prTitle,
      body: prBody,
      head: task.branch,
      draft: isDraft,
      dryRun: input.dry_run || false,
    });

    if (isFailure(createPrResult)) {
      return {
        content: [
          { type: 'text', text: JSON.stringify({ error: createPrResult.error }) },
        ],
        isError: true,
      };
    }

    const pr = createPrResult.data;

    // 3) Update task status and log event (retry only DB writes)
    const updateTaskResult = await withRetry(async () =>
      prisma.task.update({
        where: { id: input.task_id },
        data: { status: 'review', updatedAt: new Date() },
      })
    );
    if (isFailure(updateTaskResult)) {
      return {
        content: [
          { type: 'text', text: JSON.stringify({ error: updateTaskResult.error }) },
        ],
        isError: true,
      };
    }

    await withRetry(async () =>
      prisma.event.create({
        data: {
          taskId: input.task_id,
          actor: task.assignee || 'system',
          action: 'pr_opened',
          payload: JSON.stringify({
            pr_number: pr.number,
            pr_url: pr.url,
            title: pr.title,
            draft: pr.draft,
            repo: repoString,
            branch: task.branch,
            dry_run: input.dry_run || false,
            timestamp: new Date().toISOString(),
          }),
        },
      })
    );

    const response: OpenPrResponse = {
      task_id: task.id,
      pr_number: pr.number,
      repo: repoString,
      title: pr.title,
      url: pr.url,
      draft: pr.draft,
      branch_name: pr.head.ref,
      status: 'review' as any,
      dry_run: input.dry_run || false,
      created_at: new Date().toISOString(),
    };

    logger.info('Pull request created successfully', {
      requestId,
      taskId: task.id,
      prNumber: pr.number,
      url: pr.url,
      draft: pr.draft,
      dryRun: input.dry_run,
    });

    return {
      content: [
        { type: 'text', text: JSON.stringify(response) },
      ],
    };
  } catch (error) {
    logger.error('Unexpected error in open_pr', {
      requestId,
      taskId: input.task_id,
      error: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined,
    });

    return {
      content: [
        {
          type: 'text',
          text: JSON.stringify({
            error: {
              type: 'internal',
              message: 'Internal server error while creating pull request',
              code: 'INTERNAL_ERROR',
              details: { requestId },
            },
          }),
        },
      ],
      isError: true,
    };
  }
}
